# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fifart
email: fifart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  fifart development team's page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fifart.github.io" # the base hostname & protocol for your site
twitter_username: fifartnet
github_username:  fifart
title_url: "fifart.github.io"
# Build settings
markdown: kramdown
